// Dashboard ini sengaja tanpa login. Jangan publikasikan tautan deployment atau API key di tempat umum.
const API_BASE_URL = 'https://script.google.com/macros/s/AKfycbzh4MsaPWr2B3Rnr1od5AGZo1nBJZs5S4pDp8zgD6u6XccWo0dOIUkI1mGuVkZPVu4cDg/exec';
const API_KEY = 'roti-bakar-borneo';
const palette = ['#56d383','#6ea8fe','#f6bd60','#e879a9','#a78bfa','#2dd4bf','#fb923c'];
let chart;
const rupiah = new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const number = new Intl.NumberFormat('id-ID');
const iso = d => d.toISOString().slice(0,10);
function setDefaultDates(){const end=new Date(),start=new Date();start.setDate(end.getDate()-29);startDate.value=iso(start);endDate.value=iso(end)}
async function fetchApi(action){const url=new URL(API_BASE_URL);url.searchParams.set('action',action);url.searchParams.set('api_key',API_KEY);url.searchParams.set('tanggal_mulai',startDate.value);url.searchParams.set('tanggal_selesai',endDate.value);const response=await fetch(url);if(!response.ok)throw new Error(`Server ${response.status}`);const payload=await response.json();if(!payload.success)throw new Error(payload.message||'Data tidak tersedia');return payload.data}
async function load(){errorMessage.hidden=true;refreshButton.disabled=true;refreshButton.textContent='Memuat...';try{const [dashboard,payroll]=await Promise.all([fetchApi('dashboard_analytics'),fetchApi('payroll')]);render(dashboard);renderPayroll(payroll)}catch(error){errorMessage.textContent=`Gagal memuat dashboard: ${error.message}`;errorMessage.hidden=false}finally{refreshButton.disabled=false;refreshButton.textContent='Perbarui'}}
function render(data){const totals=data.cabang.reduce((a,x)=>({roti:a.roti+x.roti_terjual,setor:a.setor+x.setor_uang,pengeluaran:a.pengeluaran+x.pengeluaran,request:a.request+x.jumlah_request}),{roti:0,setor:0,pengeluaran:0,request:0});totalRoti.textContent=number.format(totals.roti);totalSetor.textContent=rupiah.format(totals.setor);totalPengeluaran.textContent=rupiah.format(totals.pengeluaran);totalRequest.textContent=number.format(totals.request);branchTable.innerHTML=data.cabang.map(x=>`<tr><td>${escapeHtml(x.nama_cabang)}</td><td>${number.format(x.roti_terjual)}</td><td>${rupiah.format(x.setor_uang)}</td><td>${rupiah.format(x.pengeluaran)}</td><td>${number.format(x.jumlah_laporan)}</td><td>${number.format(x.jumlah_request)}</td></tr>`).join('');drawChart(data);chartHint.textContent=`${data.tanggal_mulai} s.d. ${data.tanggal_selesai}`}
function renderPayroll(items){payrollTable.innerHTML=items.length?items.map(x=>`<tr><td>${escapeHtml(x.nama)}</td><td>${number.format(x.jumlah_hari_masuk)}</td><td>${number.format(x.total_jam_kerja)} jam</td><td>${number.format(x.total_menit_terlambat)} menit</td><td>${rupiah.format(x.total_potongan)}</td><td style="color:#56d383;font-weight:800">${rupiah.format(x.gaji_bersih)}</td></tr>`).join(''):'<tr><td colspan="6" style="text-align:center;color:#a9b5ac;padding:26px">Belum ada shift selesai pada periode ini.</td></tr>'}
function drawChart(data){const dates=[...new Set(data.penjualan_harian.map(x=>x.tanggal))];const branches=data.cabang;const datasets=branches.map((branch,i)=>({label:branch.nama_cabang,data:dates.map(date=>data.penjualan_harian.find(x=>x.tanggal===date&&x.id_cabang===branch.id_cabang)?.roti_terjual||0),borderColor:palette[i%palette.length],backgroundColor:palette[i%palette.length],tension:.35,fill:false}));chart?.destroy();chart=new Chart(salesChart,{type:'line',data:{labels:dates,datasets},options:{maintainAspectRatio:false,plugins:{legend:{labels:{color:'#f4f7f4'}}},scales:{x:{ticks:{color:'#a9b5ac'},grid:{color:'#2c3b31'}},y:{beginAtZero:true,ticks:{color:'#a9b5ac'},grid:{color:'#2c3b31'}}}}})}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
refreshButton.addEventListener('click',load);setDefaultDates();load();
